services:
  frontend:
    image: codeykenny/frontend-repo:${IMAGE_TAG:-latest}
    container_name: assignment11-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - backend_network

networks:
  backend_network:
    external: true
    name: ${BACKEND_NETWORK:-backend-repo_default}